name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions  🚀
on: [push]
jobs:
  main:
    strategy:
      matrix:
        node-version: [18, 20]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Run test
        run: npm run test
      
      - name: Report Coverage
        run: npx jest --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: avocad06/-codeit-CI-pracice
